version: '3.7'

services:

    nginx:
        build:
            context: ./nginx
        restart: unless-stopped
        container_name: ${NAME}_nginx
        working_dir: /var/www/app
        environment:
            - VIRTUAL_HOST=${HOST}
        depends_on:
            - php
        volumes:
            - ${PROJECT_PATH}:/var/www/app
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-enabled/app.conf:/etc/nginx/sites-enabled/${NAME}.conf

            - ./nginx/logs/access.log:/var/log/nginx/access.log
            - ./nginx/logs/error.log:/var/log/nginx/error.log
        networks:
            - frontend
            - backend

    php:
        build:
            context: ./php
            args:
                PHP: ${PHP_VERSION}
                NAME: ${NAME}
        user: 1000:1000
        restart: unless-stopped
        container_name: ${NAME}_php
        working_dir: /var/www/app
        entrypoint:
            - /bin/bash
            - /init.sh
            - ${APP_ENV}
        environment:
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
            - VIRTUAL_PROTO=fastcgi
            - TERM=xterm-256color
        volumes:
            - ./bash/.bash_aliases:/.bash_aliases
            - ./bash/.bashrc:/.bashrc
            - ./bash/init.sh:/init.sh

            - ${COMPOSER_CONFIG_PATH}:/.composer
            - ${COMPOSER_CACHE_PATH}:/.cache/composer

            - ${YARN_CONFIG_PATH}:/.yarn
            - ${YARN_CACHE_PATH}:/.cache/yarn
            - ${YARNRC_PATH}:/.yarnrc

            - ${PROJECT_PATH}:/var/www/app
        networks:
            - sql
            - backend

networks:
    frontend:
        external:
            name: ${PROXY_NETWORK_NAME}
    backend:
        driver: bridge
        name: ${NAME}_backend_network
    sql:
        external:
            name: ${SQL_NETWORK_NAME}
